# Generated by Django 3.2 on 2021-04-29 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актеры и режисcеры', 'verbose_name_plural': 'Актеры и режисcеры'},
        ),
        migrations.AlterField(
            model_name='movies',
            name='world_premiere',
            field=models.DateField(default=datetime.date.today, verbose_name='Премьера в мире'),
        ),
    ]
